This one is pertinent, it make the test find the mpi library on MAC OS X.
git-svn-id: https://svn.open-mpi.org/svn/ompi-tests/trunk@459 91b169b6-37d5-0310-8fc8-d193d6184df4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4212,6 +4212,14 @@ echo "$as_me: error: neither libmpi nor libmpi_ss found; check path for MPI pack
    { (exit 1); exit 1; }; }
     fi
   ;;
+  *-apple-*)                     if test -f "$mpi_lib_dir/libmpi.dylib" ; then
+      lib_mpi="mpi"
+    else
+      { { echo "$as_me:$LINENO: error: neither libmpi nor libmpi_ss found; check path for MPI package first..." >&5
+echo "$as_me: error: neither libmpi nor libmpi_ss found; check path for MPI package first..." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  ;;
   *)                             if test -f "$mpi_lib_dir/libmpi.a" ; then
       lib_mpi="mpi"
     elif test -f "$mpi_lib_dir/libmpi.so" ; then
